version: '3.9'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - '.:/app'
    depends_on:
      - php-fpm
  php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
    environment:
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - '.:/app'
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - '.:/app'